name: "🐛 Bug Report"
description: Report implementation errors, unexpected behavior, or structural inconsistencies.
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for improving Project Mech-Wolf.
        Please provide structured details. Avoid vague reports.

  - type: input
    id: environment
    attributes:
      label: Environment
      description: OS / Python version / Browser / Commit hash
      placeholder: e.g. Ubuntu 22.04, Python 3.11, commit 8f3a2c1

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: What happened?
      placeholder: Clear and reproducible description.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should have happened?

  - type: textarea
    id: logs
    attributes:
      label: Logs / Traceback
      description: Paste relevant logs.
      render: shell

  - type: textarea
    id: hypothesis
    attributes:
      label: Hypothesis (Optional)
      description: Any architectural guess?