name: "🚀 Feature Proposal"
description: Propose new mechanisms, extensions, or structural experiments.
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Features must align with the philosophy:
        Evolution by pruning, not accumulation.

  - type: textarea
    id: proposal
    attributes:
      label: Proposal Summary
      description: What are you proposing?
    validations:
      required: true

  - type: textarea
    id: alignment
    attributes:
      label: Architectural Alignment
      description: How does this align with Constitutional constraints?

  - type: textarea
    id: cost
    attributes:
      label: Cost & Irreversibility
      description: What structural cost does this introduce?

  - type: textarea
    id: expected_impact
    attributes:
      label: Expected Impact
      description: What measurable change should occur?